### ISSUE TITLE
The GitHub Icon NavLink  on the header is not directing to the main page

### ISSUE THREAD

**Issue by Polymath0033** [jimoh-sodiq/VuePatterns#4]
<img width="932" alt="image" src="https://github.com/user-attachments/assets/3b234fa9-ccc2-4127-acd2-1e55ad8cbb4a">
The github icon is direction to [vitepress](https://github.com/vuejs/vitepress)

**Comment by jimoh-sodiq** [comment]
thanks, I have replaced the github link with the correct one

**Comment by Polymath0033** [comment]
Alright! well done, chief!
